/* Generated By:JavaCC: Do not edit this line. AssignmentConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AssignmentConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 1;
  /** RegularExpression Id. */
  int MULT = 2;
  /** RegularExpression Id. */
  int LBRAC = 3;
  /** RegularExpression Id. */
  int RBRAC = 4;
  /** RegularExpression Id. */
  int LCURL = 5;
  /** RegularExpression Id. */
  int RCURL = 6;
  /** RegularExpression Id. */
  int KDEF = 7;
  /** RegularExpression Id. */
  int EOL = 8;
  /** RegularExpression Id. */
  int SPACE = 9;
  /** RegularExpression Id. */
  int SCOLN = 10;
  /** RegularExpression Id. */
  int MFUNC = 11;
  /** RegularExpression Id. */
  int NFUNC = 12;
  /** RegularExpression Id. */
  int PARAM = 13;
  /** RegularExpression Id. */
  int NUM = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"+\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"DEF\"",
    "<EOL>",
    "\" \"",
    "\";\"",
    "\"MAIN\"",
    "<NFUNC>",
    "<PARAM>",
    "<NUM>",
  };

}
